-- Lookup rows a dev database needs on top of test-reference-data.sql:
-- countries, currencies, Stripe test-mode products and prices, tutorial
-- levels and categories, and so on. Load after pyangelo-schema.sql and
-- test-reference-data.sql. No people, sketches or other production data.
-- Generated from the rows the numbered migrations insert.

SET foreign_key_checks=0;
INSERT INTO `blog_category` (`blog_category_id`, `description`) VALUES (1,'PyAngelo Advice');
INSERT INTO `blog_category` (`blog_category_id`, `description`) VALUES (2,'PyAngelo News');
INSERT INTO `blog_category` (`blog_category_id`, `description`) VALUES (3,'Coding Tips');
INSERT INTO `blog_category` (`blog_category_id`, `description`) VALUES (4,'Coding Ideas');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('A1','Anonymous Proxy','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('A2','Satellite Provider','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('AD','Andorra','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('AE','United Arab Emirates','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('AF','Afghanistan','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('AG','Antigua and Barbuda','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('AI','Anguilla','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('AL','Albania','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('AM','Armenia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('AO','Angola','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('AP','Asia/Pacific Region','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('AQ','Antarctica','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('AR','Argentina','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('AS','American Samoa','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('AT','Austria','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('AU','Australia','AUD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('AW','Aruba','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('AX','Aland Islands','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('AZ','Azerbaijan','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BA','Bosnia and Herzegovina','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BB','Barbados','BBD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BD','Bangladesh','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BE','Belgium','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BF','Burkina Faso','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BG','Bulgaria','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BH','Bahrain','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BI','Burundi','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BJ','Benin','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BL','Saint Bartelemey','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BM','Bermuda','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BN','Brunei Darussalam','BND');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BO','Bolivia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BQ','Bonaire, Saint Eustatius and Saba','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BR','Brazil','BRL');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BS','Bahamas','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BT','Bhutan','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BV','Bouvet Island','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BW','Botswana','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BY','Belarus','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('BZ','Belize','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CA','Canada','CAD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CC','Cocos (Keeling) Islands','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CD','Congo, The Democratic Republic of the','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CF','Central African Republic','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CG','Congo','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CH','Switzerland','CHF');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CI','Cote d\'Ivoire','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CK','Cook Islands','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CL','Chile','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CM','Cameroon','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CN','China','CNY');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CO','Colombia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CR','Costa Rica','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CU','Cuba','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CV','Cape Verde','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CW','Curacao','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CX','Christmas Island','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CY','Cyprus','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('CZ','Czech Republic','CZK');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('DE','Germany','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('DJ','Djibouti','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('DK','Denmark','DKK');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('DM','Dominica','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('DO','Dominican Republic','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('DZ','Algeria','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('EC','Ecuador','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('EE','Estonia','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('EG','Egypt','EGP');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('EH','Western Sahara','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('ER','Eritrea','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('ES','Spain','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('ET','Ethiopia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('EU','Europe','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('FI','Finland','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('FJ','Fiji','FJD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('FK','Falkland Islands (Malvinas)','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('FM','Micronesia, Federated States of','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('FO','Faroe Islands','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('FR','France','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GA','Gabon','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GB','United Kingdom','GBP');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GD','Grenada','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GE','Georgia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GF','French Guiana','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GG','Guernsey','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GH','Ghana','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GI','Gibraltar','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GL','Greenland','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GM','Gambia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GN','Guinea','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GP','Guadeloupe','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GQ','Equatorial Guinea','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GR','Greece','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GS','South Georgia and the South Sandwich Islands','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GT','Guatemala','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GU','Guam','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GW','Guinea-Bissau','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('GY','Guyana','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('HK','Hong Kong','HKD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('HM','Heard Island and McDonald Islands','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('HN','Honduras','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('HR','Croatia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('HT','Haiti','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('HU','Hungary','HUF');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('ID','Indonesia','IDR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('IE','Ireland','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('IL','Israel','ILS');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('IM','Isle of Man','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('IN','India','INR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('IO','British Indian Ocean Territory','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('IQ','Iraq','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('IR','Iran, Islamic Republic of','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('IS','Iceland','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('IT','Italy','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('JE','Jersey','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('JM','Jamaica','JMD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('JO','Jordan','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('JP','Japan','JPY');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('KE','Kenya','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('KG','Kyrgyzstan','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('KH','Cambodia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('KI','Kiribati','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('KM','Comoros','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('KN','Saint Kitts and Nevis','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('KP','Korea, Democratic People\'s Republic of','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('KR','Korea, Republic of','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('KW','Kuwait','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('KY','Cayman Islands','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('KZ','Kazakhstan','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('LA','Lao People\'s Democratic Republic','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('LB','Lebanon','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('LC','Saint Lucia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('LI','Liechtenstein','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('LK','Sri Lanka','LKR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('LR','Liberia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('LS','Lesotho','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('LT','Lithuania','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('LU','Luxembourg','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('LV','Latvia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('LY','Libyan Arab Jamahiriya','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MA','Morocco','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MC','Monaco','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MD','Moldova, Republic of','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('ME','Montenegro','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MF','Saint Martin','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MG','Madagascar','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MH','Marshall Islands','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MK','Macedonia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('ML','Mali','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MM','Myanmar','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MN','Mongolia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MO','Macao','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MP','Northern Mariana Islands','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MQ','Martinique','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MR','Mauritania','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MS','Montserrat','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MT','Malta','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MU','Mauritius','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MV','Maldives','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MW','Malawi','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MX','Mexico','MXN');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MY','Malaysia','MYR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('MZ','Mozambique','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('NA','Namibia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('NC','New Caledonia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('NE','Niger','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('NF','Norfolk Island','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('NG','Nigeria','NGN');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('NI','Nicaragua','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('NL','Netherlands','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('NO','Norway','NOK');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('NP','Nepal','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('NR','Nauru','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('NU','Niue','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('NZ','New Zealand','NZD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('O1','Other Country','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('OM','Oman','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('PA','Panama','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('PE','Peru','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('PF','French Polynesia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('PG','Papua New Guinea','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('PH','Philippines','PHP');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('PK','Pakistan','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('PL','Poland','PLN');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('PM','Saint Pierre and Miquelon','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('PN','Pitcairn','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('PR','Puerto Rico','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('PS','Palestinian Territory','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('PT','Portugal','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('PW','Palau','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('PY','Paraguay','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('QA','Qatar','QAR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('RE','Reunion','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('RO','Romania','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('RS','Serbia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('RU','Russian Federation','RUB');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('RW','Rwanda','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SA','Saudi Arabia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SB','Solomon Islands','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SC','Seychelles','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SD','Sudan','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SE','Sweden','SEK');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SG','Singapore','SGD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SH','Saint Helena','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SI','Slovenia','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SJ','Svalbard and Jan Mayen','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SK','Slovakia','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SL','Sierra Leone','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SM','San Marino','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SN','Senegal','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SO','Somalia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SR','Suriname','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('ST','Sao Tome and Principe','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SV','El Salvador','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SX','Sint Maarten','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SY','Syrian Arab Republic','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('SZ','Swaziland','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('TC','Turks and Caicos Islands','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('TD','Chad','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('TF','French Southern Territories','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('TG','Togo','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('TH','Thailand','THB');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('TJ','Tajikistan','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('TK','Tokelau','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('TL','Timor-Leste','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('TM','Turkmenistan','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('TN','Tunisia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('TO','Tonga','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('TR','Turkey','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('TT','Trinidad and Tobago','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('TV','Tuvalu','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('TW','Taiwan','TWD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('TZ','Tanzania, United Republic of','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('UA','Ukraine','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('UG','Uganda','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('UM','United States Minor Outlying Islands','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('US','United States','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('UY','Uruguay','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('UZ','Uzbekistan','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('VA','Holy See (Vatican City State)','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('VC','Saint Vincent and the Grenadines','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('VE','Venezuela','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('VG','Virgin Islands, British','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('VI','Virgin Islands, U.S.','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('VN','Vietnam','VND');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('VU','Vanuatu','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('WF','Wallis and Futuna','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('WS','Samoa','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('YE','Yemen','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('YT','Mayotte','EUR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('ZA','South Africa','ZAR');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('ZM','Zambia','USD');
INSERT INTO `country` (`country_code`, `country_name`, `currency_code`) VALUES ('ZW','Zimbabwe','USD');
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('AUD','Australian Dollars','$',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('BBD','Barbadian Dollars','Bds$',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('BND','Brunei Dollars','B$',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('BRL','Brazilian Real','R$',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('CAD','Canadian Dollars','$',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('CHF','Swiss Francs','CHF',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('CNY','Chinese Renminbi','&yen;',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('CZK','Czech Republic Korunas','Kč ',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('DKK','Danish Kroner','kr ',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('EGP','Egyptian Pounds','E£',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('EUR','Euros','&euro;',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('FJD','Fijian Dollars','FJ$',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('GBP','British Pounds','&pound;',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('HKD','Hong Kong Dollars','HK$',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('HUF','Hungarian Forint','Ft ',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('IDR','Indonesian Rupiah','Rp',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('ILS','Israeli New Sheqels','₪',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('INR','Indian Rupees','₹',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('JMD','Jamaican Dollars','J$',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('JPY','Japanese Yen','&yen;',1);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('LKR','Sri Lankan Rupees','Ɍs',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('MXN','Mexican Pesos','$',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('MYR','Malaysian Ringgit','RM',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('NGN','Nigerian Naira','&#8358;',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('NOK','Norwegian Kroner','kr ',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('NZD','New Zealand Dollars','$',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('PHP','Philippine Pesos','₱',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('PLN','Polish Zloty','zł',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('QAR','Qatari Riyal','ر.ق',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('RUB','Russian Ruble','₽',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('SEK','Swedish Kronor','kr ',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('SGD','Singapore Dollars','$',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('THB','Thai Baht','฿',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('TWD','New Taiwan Dollars','NT$',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('USD','US Dollars','$',100);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('VND','Vietnamese Đồng','&#8363;',1);
INSERT INTO `currency` (`currency_code`, `currency_description`, `currency_symbol`, `stripe_divisor`) VALUES ('ZAR','South African Rand','R',100);
INSERT INTO `lesson_security_level` (`lesson_security_level_id`, `description`) VALUES (1,'Anyone');
INSERT INTO `lesson_security_level` (`lesson_security_level_id`, `description`) VALUES (2,'Free members');
INSERT INTO `lesson_security_level` (`lesson_security_level_id`, `description`) VALUES (3,'Premium members');
INSERT INTO `question_type` (`question_type_id`, `description`, `category_slug`) VALUES (1,'General','general');
INSERT INTO `question_type` (`question_type_id`, `description`, `category_slug`) VALUES (2,'PyAngelo','pyangelo');
INSERT INTO `question_type` (`question_type_id`, `description`, `category_slug`) VALUES (3,'Tutorials','tutorials');
INSERT INTO `question_type` (`question_type_id`, `description`, `category_slug`) VALUES (4,'Algorithms','algorithms');
INSERT INTO `question_type` (`question_type_id`, `description`, `category_slug`) VALUES (5,'Loops','loops');
INSERT INTO `question_type` (`question_type_id`, `description`, `category_slug`) VALUES (6,'Conditionals','conditionals');
INSERT INTO `question_type` (`question_type_id`, `description`, `category_slug`) VALUES (7,'Variables','variables');
INSERT INTO `question_type` (`question_type_id`, `description`, `category_slug`) VALUES (8,'Functions','functions');
INSERT INTO `question_type` (`question_type_id`, `description`, `category_slug`) VALUES (9,'Website','website');
INSERT INTO `question_type` (`question_type_id`, `description`, `category_slug`) VALUES (10,'Discussion','discussion');
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjmAkvBrl8hmb43SvuzZA','prod_JvIKdSouFisljN','VND',140000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjmAkvBrl8hmb5RI4cfPL','prod_JvIKdSouFisljN','PLN',2495,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjmAkvBrl8hmbBhqzccnN','prod_JvIKdSouFisljN','PHP',30000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjmAkvBrl8hmbCqNoWFRE','prod_JvIKdSouFisljN','ZAR',8995,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjmAkvBrl8hmbHDV59G12','prod_JvIKdSouFisljN','SGD',995,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjmAkvBrl8hmbhpscKYWY','prod_JvIKdSouFisljN','SEK',6495,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjmAkvBrl8hmbqEJ3R1AD','prod_JvIKdSouFisljN','TWD',20000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjmAkvBrl8hmbR2Okb5UG','prod_JvIKdSouFisljN','NZD',995,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjmAkvBrl8hmbtc4GIFOI','prod_JvIKdSouFisljN','USD',695,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjmAkvBrl8hmbtQjpapa3','prod_JvIKdSouFisljN','RUB',40000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjmAkvBrl8hmbX0uE6vV5','prod_JvIKdSouFisljN','QAR',2495,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjmAkvBrl8hmbYrtENUqI','prod_JvIKdSouFisljN','THB',22000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmb0v6Nhru9','prod_JvIKdSouFisljN','HKD',5495,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmb1deN56Rv','prod_JvIKdSouFisljN','INR',40000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmb2byDLxdh','prod_JvIKdSouFisljN','IDR',9000000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmb8p9TiZQo','prod_JvIKdSouFisljN','EGP',13000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmb8vNUM4Pz','prod_JvIKdSouFisljN','NGN',200000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmb9PcvHSy3','prod_JvIKdSouFisljN','LKR',100000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmbbxAjQFf5','prod_JvIKdSouFisljN','FJD',1495,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmbC724Lrj4','prod_JvIKdSouFisljN','CZK',15000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmbeliM2jMb','prod_JvIKdSouFisljN','EUR',695,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmbEnpEcGme','prod_JvIKdSouFisljN','HUF',200000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmbG98tu684','prod_JvIKdSouFisljN','ILS',2495,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmbgW4PQarY','prod_JvIKdSouFisljN','BND',995,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmbH4kYgyzV','prod_JvIKdSouFisljN','JPY',800,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmbhFsWXdn7','prod_JvIKdSouFisljN','DKK',4995,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmbIb9bAnul','prod_JvIKdSouFisljN','JMD',90000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmbjBdW2WCc','prod_JvIKdSouFisljN','BBD',1395,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmblae0hDEL','prod_JvIKdSouFisljN','CHF',750,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmblgjQX7cL','prod_JvIKdSouFisljN','BRL',2195,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmboMJAO09k','prod_JvIKdSouFisljN','MYR',2495,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmbPqVFxS6R','prod_JvIKdSouFisljN','NOK',5995,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmbshS6vBng','prod_JvIKdSouFisljN','MXN',12000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmbtr8z7xhZ','prod_JvIKdSouFisljN','GBP',595,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmbvoHZyvTX','prod_JvIKdSouFisljN','CAD',995,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjnAkvBrl8hmbzfVKlGtM','prod_JvIKdSouFisljN','CNY',4495,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1JHRjoAkvBrl8hmbrUY2LzFc','prod_JvIKdSouFisljN','AUD',995,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65mAkvBrl8hmb5e80sENu','prod_M18MmyAl5aUI8u','CNY',6750,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65mAkvBrl8hmbeoVkws4R','prod_M18MmyAl5aUI8u','BRL',3295,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65mAkvBrl8hmblCbKMytQ','prod_M18MmyAl5aUI8u','CZK',22500,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65mAkvBrl8hmbln6Dt8HV','prod_M18MmyAl5aUI8u','BND',1495,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65mAkvBrl8hmbnmg3N9E5','prod_M18MmyAl5aUI8u','BBD',1995,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65mAkvBrl8hmbQGrEkLhO','prod_M18MmyAl5aUI8u','CHF',1125,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65mAkvBrl8hmbRPhzYpfC','prod_M18MmyAl5aUI8u','CAD',1495,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65mAkvBrl8hmbv3qa97KE','prod_M18MmyAl5aUI8u','AUD',1495,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65nAkvBrl8hmb5czQMkSs','prod_M18MmyAl5aUI8u','GBP',895,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65nAkvBrl8hmbdHOG24jF','prod_M18MmyAl5aUI8u','ILS',3695,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65nAkvBrl8hmbg60GlkBB','prod_M18MmyAl5aUI8u','HKD',7995,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65nAkvBrl8hmbKvCG9zzZ','prod_M18MmyAl5aUI8u','FJD',2250,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65nAkvBrl8hmbl4nIKv2B','prod_M18MmyAl5aUI8u','DKK',7495,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65nAkvBrl8hmbLlCymQTk','prod_M18MmyAl5aUI8u','JPY',1200,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65nAkvBrl8hmbNZru3lFc','prod_M18MmyAl5aUI8u','INR',60000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65nAkvBrl8hmbpBNtIXLC','prod_M18MmyAl5aUI8u','HUF',300000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65nAkvBrl8hmbRItlT9dx','prod_M18MmyAl5aUI8u','EGP',19500,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65nAkvBrl8hmbVw0TzcvF','prod_M18MmyAl5aUI8u','IDR',13500000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65nAkvBrl8hmbY1LLHjue','prod_M18MmyAl5aUI8u','JMD',135000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65nAkvBrl8hmbZE1a9YzR','prod_M18MmyAl5aUI8u','EUR',995,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65oAkvBrl8hmb8gl2gBfw','prod_M18MmyAl5aUI8u','MXN',18000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65oAkvBrl8hmb9fJi3LkL','prod_M18MmyAl5aUI8u','NGN',300000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65oAkvBrl8hmbdQ8YsNIR','prod_M18MmyAl5aUI8u','SGD',1495,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65oAkvBrl8hmbE9jQ9MaP','prod_M18MmyAl5aUI8u','NZD',1495,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65oAkvBrl8hmbfQz1IBWN','prod_M18MmyAl5aUI8u','LKR',150000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65oAkvBrl8hmbGln7r6sZ','prod_M18MmyAl5aUI8u','PHP',45000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65oAkvBrl8hmbGqMvlDbN','prod_M18MmyAl5aUI8u','QAR',3695,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65oAkvBrl8hmbHmrgLt4m','prod_M18MmyAl5aUI8u','RUB',60000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65oAkvBrl8hmbJ2VAeiWi','prod_M18MmyAl5aUI8u','NOK',8995,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65oAkvBrl8hmbmJEiqhLW','prod_M18MmyAl5aUI8u','PLN',3695,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65oAkvBrl8hmbpC1Ddqmx','prod_M18MmyAl5aUI8u','THB',33000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65oAkvBrl8hmbTft52KWX','prod_M18MmyAl5aUI8u','MYR',3695,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65oAkvBrl8hmbvn2mYwfY','prod_M18MmyAl5aUI8u','TWD',30000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65pAkvBrl8hmb1wBO7d27','prod_M18MmyAl5aUI8u','SEK',9995,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65pAkvBrl8hmbCAYHQJwZ','prod_M18MmyAl5aUI8u','VND',210000,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65pAkvBrl8hmbihcQCMGf','prod_M18MmyAl5aUI8u','USD',995,'month',1);
INSERT INTO `stripe_price` (`stripe_price_id`, `stripe_product_id`, `currency_code`, `price_in_cents`, `billing_period`, `active`) VALUES ('price_1LJ65pAkvBrl8hmbn7IwrBXw','prod_M18MmyAl5aUI8u','ZAR',13595,'month',1);
INSERT INTO `stripe_product` (`stripe_product_id`, `product_name`, `product_description`, `active`) VALUES ('prod_JvIKdSouFisljN','Full Access','Provides full access to every PyAngelo tutorial',1);
INSERT INTO `stripe_product` (`stripe_product_id`, `product_name`, `product_description`, `active`) VALUES ('prod_M18MmyAl5aUI8u','Full Access Plus','Provides full access to every PyAngelo tutorial plus increases the maximum upload size of assets from 8MB to 64MB.',1);
INSERT INTO `tutorial_category` (`tutorial_category_id`, `category`, `category_slug`, `display_order`) VALUES (1,'Introduction to Programming','introduction-to-programming',1);
INSERT INTO `tutorial_category` (`tutorial_category_id`, `category`, `category_slug`, `display_order`) VALUES (2,'Arcade Games','arcade-games',2);
INSERT INTO `tutorial_category` (`tutorial_category_id`, `category`, `category_slug`, `display_order`) VALUES (3,'Coding Challenges','coding-challenges',3);
INSERT INTO `tutorial_level` (`tutorial_level_id`, `description`) VALUES (1,'Beginner');
INSERT INTO `tutorial_level` (`tutorial_level_id`, `description`) VALUES (2,'Intermediate');
INSERT INTO `tutorial_level` (`tutorial_level_id`, `description`) VALUES (3,'Advanced');
SET foreign_key_checks=1;
